version: '3'
services:
  app:
    container_name: app_vuttr
    build: .
    command: npm run ci
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo_test_vuttr
    image: mongo
    ports:
      - '27017:27017'