version: '3'
services:
  app:
    container_name: app_vuttr
    restart: always
    build: .
    command: npm start
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo_vuttr
    image: mongo
    ports:
      - '27017:27017'